version: '3.9'

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "8884:8884"

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "8882:8882"

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "8883:8883"

  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    ports:
      - "8881:8881"
